<?php
require_once '../conjugate.php';
class EtrePassiveTest extends PHPUnit_Framework_TestCase {
	/**
	 * @dataProvider EtrePassiveTestProvider
	 */
	public function testEtrePassive($expectedResult, $person,$tense,$mood, $voice) {
		$this->assertEquals ( $expectedResult, etre_passive(new Person($person), new Tense($tense), new Mood($mood), new Voice($voice)));
	}
	public function EtrePassiveTestProvider() {
		return [
				[
						'suis',
						Person::FirstPersonSingular,
						Tense::Present,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'es',
						Person::SecondPersonSingular,
						Tense::Present,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'est',
						Person::ThirdPersonSingular,
						Tense::Present,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'sommes',
						Person::FirstPersonPlural,
						Tense::Present,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'êtes',
						Person::SecondPersonPlural,
						Tense::Present,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'sont',
						Person::ThirdPersonPlural,
						Tense::Present,
						Mood::Indicatif,
						Voice::Passive,						
				],
				
				[
						'étais',
						Person::FirstPersonSingular,
						Tense::Imparfait,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'étais',
						Person::SecondPersonSingular,
						Tense::Imparfait,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'était',
						Person::ThirdPersonSingular,
						Tense::Imparfait,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'étions',
						Person::FirstPersonPlural,
						Tense::Imparfait,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'étiez',
						Person::SecondPersonPlural,
						Tense::Imparfait,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'étaient',
						Person::ThirdPersonPlural,
						Tense::Imparfait,
						Mood::Indicatif,
						Voice::Passive,						
				],	

				[
						'fus',
						Person::FirstPersonSingular,
						Tense::Passe,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'fus',
						Person::SecondPersonSingular,
						Tense::Passe,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'fut',
						Person::ThirdPersonSingular,
						Tense::Passe,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'fûmes',
						Person::FirstPersonPlural,
						Tense::Passe,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'fûtes',
						Person::SecondPersonPlural,
						Tense::Passe,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'furent',
						Person::ThirdPersonPlural,
						Tense::Passe,
						Mood::Indicatif,
						Voice::Passive,						
				],	

				[
						'serai',
						Person::FirstPersonSingular,
						Tense::Futur,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'seras',
						Person::SecondPersonSingular,
						Tense::Futur,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'sera',
						Person::ThirdPersonSingular,
						Tense::Futur,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'serons',
						Person::FirstPersonPlural,
						Tense::Futur,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'serez',
						Person::SecondPersonPlural,
						Tense::Futur,
						Mood::Indicatif,
						Voice::Passive,						
				],
				[
						'seront',
						Person::ThirdPersonPlural,
						Tense::Futur,
						Mood::Indicatif,
						Voice::Passive,						
				],	


				[
						'sois',
						Person::FirstPersonSingular,
						Tense::Present,
						Mood::Subjonctif,
						Voice::Passive,						
				],
				[
						'sois',
						Person::SecondPersonSingular,
						Tense::Present,
						Mood::Subjonctif,
						Voice::Passive,						
				],
				[
						'soit',
						Person::ThirdPersonSingular,
						Tense::Present,
						Mood::Subjonctif,
						Voice::Passive,						
				],
				[
						'soyons',
						Person::FirstPersonPlural,
						Tense::Present,
						Mood::Subjonctif,
						Voice::Passive,						
				],
				[
						'soyez',
						Person::SecondPersonPlural,
						Tense::Present,
						Mood::Subjonctif,
						Voice::Passive,						
				],
				[
						'soient',
						Person::ThirdPersonPlural,
						Tense::Present,
						Mood::Subjonctif,
						Voice::Passive,						
				],	
				
				[
						'fusse',
						Person::FirstPersonSingular,
						Tense::Imparfait,
						Mood::Subjonctif,
						Voice::Passive,						
				],
				[
						'fusses',
						Person::SecondPersonSingular,
						Tense::Imparfait,
						Mood::Subjonctif,
						Voice::Passive,						
				],
				[
						'fût',
						Person::ThirdPersonSingular,
						Tense::Imparfait,
						Mood::Subjonctif,
						Voice::Passive,						
				],
				[
						'fussions',
						Person::FirstPersonPlural,
						Tense::Imparfait,
						Mood::Subjonctif,
						Voice::Passive,						
				],
				[
						'fussiez',
						Person::SecondPersonPlural,
						Tense::Imparfait,
						Mood::Subjonctif,
						Voice::Passive,						
				],
				[
						'fussent',
						Person::ThirdPersonPlural,
						Tense::Imparfait,
						Mood::Subjonctif,
						Voice::Passive,						
				],
			

				[
						'serais',
						Person::FirstPersonSingular,
						Tense::Present,
						Mood::Conditionnel,
						Voice::Passive,						
				],
				[
						'serais',
						Person::SecondPersonSingular,
						Tense::Present,
						Mood::Conditionnel,
						Voice::Passive,						
				],
				[
						'serait',
						Person::ThirdPersonSingular,
						Tense::Present,
						Mood::Conditionnel,
						Voice::Passive,						
				],
				[
						'serions',
						Person::FirstPersonPlural,
						Tense::Present,
						Mood::Conditionnel,
						Voice::Passive,						
				],
				[
						'seriez',
						Person::SecondPersonPlural,
						Tense::Present,
						Mood::Conditionnel,
						Voice::Passive,						
				],
				[
						'seraient',
						Person::ThirdPersonPlural,
						Tense::Present,
						Mood::Conditionnel,
						Voice::Passive,						
				],		



				[
						'sois',
						Person::SecondPersonSingular,
						Tense::Present,
						Mood::Imperatif,
						Voice::Passive,						
				],
				[
						'soyons',
						Person::FirstPersonPlural,
						Tense::Present,
						Mood::Imperatif,
						Voice::Passive,						
				],
				[
						'soyez',
						Person::SecondPersonPlural,
						Tense::Present,
						Mood::Imperatif,
						Voice::Passive,						
				],
				
		];
	}
}

