<?php
require_once '../conjugate.php';
class ExceptionModelTest extends PHPUnit_Framework_TestCase {
	
	/**
	 * @dataProvider ExceptionModelTestProvider
	 */
	public function testConjugationModelTest($expectedResult, $infinitiveVerb) {
		$this->assertEquals ( new ExceptionModel ( $expectedResult ), finding_exception_model ( new InfinitiveVerb ( $infinitiveVerb ) ) );
	}
	public function ExceptionModelTestProvider() {
		return [
				[
						ExceptionModel::Eler_Ele,
						'peler' 
				],
				[
						ExceptionModel::Eter_Ete,
						'acheter' 
				],
				
				[
						ExceptionModel::Eler_Elle,
						'appeler' 
				],
				[
						ExceptionModel::Eter_Ette,
						'jeter' 
				],
				[
						ExceptionModel::E_Akut_Er,
						'sécher' 
				],
				[
						ExceptionModel::E_Akut_Er,
						'espérer' 
				],
				[
						ExceptionModel::E_Akut_Er,
						'accélérer' 
				],
				[
						ExceptionModel::E_Er,
						'peser' 
				],
				[
						ExceptionModel::CER,
						'agacer' 
				],
				[
						ExceptionModel::GER,
						'manger' 
				],
				[
						ExceptionModel::ENVOYER,
						'envoyer' 
				],
				[
						ExceptionModel::DEVOIR,
						'devoir' 
				],
				[
						ExceptionModel::MOUVOIR,
						'mouvoir' 
				],
				[
						ExceptionModel::POUVOIR,
						'pouvoir' 
				],
				[
						ExceptionModel::SAVOIR,
						'savoir' 
				],
				[
						ExceptionModel::COURIR,
						'courir' 
				],
				[
						ExceptionModel::MOURIR,
						'mourir' 
				],
				[
						ExceptionModel::QUERIR,
						'acquérir' 
				],
				[
						ExceptionModel::DORMIR,
						'dormir' 
				],
				[
						ExceptionModel::TIR,
						'assentir' 
				],
				[
						ExceptionModel::RIR,
						'couvrir' 
				],
				[
						ExceptionModel::SERVIR,
						'servir' 
				],
				[
						ExceptionModel::ENIR,
						'tenir' 
				],
				[
						ExceptionModel::FUIR,
						'fuir' 
				],
				[
						ExceptionModel::BOUILLIR,
						'bouillir' 
				],
				[
						ExceptionModel::SAILLIR,
						'saillir' 
				],
				[
						ExceptionModel::VALOIR,
						'valoir' 
				],
				[
						ExceptionModel::VOIR,
						'voir' 
				],
				[
						ExceptionModel::VOIR,
						'prévoir' 
				],
				[
						ExceptionModel::VOIR,
						'pourvoir' 
				],
				[
						ExceptionModel::CUEILLIR,
						'cueillir' 
				],
				[
						ExceptionModel::VETIR,
						'vêtir' 
				] 
		];
	}
}

?>