<?php
require_once '../conjugate.php';
class ModeImpersonnelsTest extends PHPUnit_Framework_TestCase {
	
	/**
	 * @dataProvider modeImpersonnelsTestProvider
	 */
	public function testModeImpersonnels($expectedResult, $infinitiveVerb, $auxiliaire, $mode, $tense, $gender, $voice) {
		$this->assertEquals ( $expectedResult, modes_impersonnels ( new InfinitiveVerb( $infinitiveVerb), new Auxiliaire ( $auxiliaire ), new Mode ( $mode ), new Tense ( $tense ), new Gender ( $gender ),new Voice ( $voice ) ) );
	}
	public function modeImpersonnelsTestProvider() {
		;
		return [
				[
						'aimer',
						'aimer',
						Auxiliaire::Avoir,
						'Infinitif',
						'Present',
						Gender::Masculine,
						Voice::Active,						
				],
				[
						'être aimé',
						'aimer',
						Auxiliaire::Avoir,
						'Infinitif',
						'Present',
						Gender::Masculine,
						Voice::Passive,						
				],				
				[
						'avoir aimé',
						'aimer',
						Auxiliaire::Avoir,
						'Infinitif',
						'Passe',
						Gender::Masculine,
						Voice::Active,							
				],
				[
						'avoir été aimé',
						'aimer',
						Auxiliaire::Avoir,
						'Infinitif',
						'Passe',
						Gender::Masculine,
						Voice::Passive,							
				],				
				[
						'en aimant',
						'aimer',
						Auxiliaire::Avoir,
						'Gerondif',
						'Present',
						Gender::Masculine,
						Voice::Active,							
				],
				[
						'en ayant aimé',
						'aimer',
						Auxiliaire::Avoir,
						'Gerondif',
						'Passe',
						Gender::Masculine,
						Voice::Active,							
				],
				[
						'aimant',
						'aimer',
						Auxiliaire::Avoir,
						'Participe',
						'Present',
						Gender::Masculine,
						Voice::Active,							
				],
				[
						'aimé',
						'aimer',
						Auxiliaire::Avoir,
						'Participe',
						'Passe',
						Gender::Masculine,
						Voice::Active,							
				],
				
				[
						'amuser',
						'amuser',
						Auxiliaire::Etre,
						'Infinitif',
						'Present',
						Gender::Masculine,
						Voice::Active,							
				],
				[
						'être amusé',
						'amuser',
						Auxiliaire::Etre,
						'Infinitif',
						'Passe',
						Gender::Masculine,
						Voice::Active,							
				],
				[
						'être amusée',
						'amuser',
						Auxiliaire::Etre,
						'Infinitif',
						'Passe',
						Gender::Feminine,
						Voice::Active,							
				],				
				[
						'en amusant',
						'amuser',
						Auxiliaire::Etre,
						'Gerondif',
						'Present',
						Gender::Masculine,
						Voice::Active,							
				],
				[
						'en étant amusé',
						'amuser',
						Auxiliaire::Etre,
						'Gerondif',
						'Passe',
						Gender::Masculine,
						Voice::Active,							
				],
				[
						'en étant amusée',
						'amuser',
						Auxiliaire::Etre,
						'Gerondif',
						'Passe',
						Gender::Feminine,
						Voice::Active,							
				],	
				[
						'en étant été amusé',
						'amuser',
						Auxiliaire::Etre,
						'Gerondif',
						'Passe',
						Gender::Masculine,
						Voice::Passive,							
				],
				[
						'en étant été amusée',
						'amuser',
						Auxiliaire::Etre,
						'Gerondif',
						'Passe',
						Gender::Feminine,
						Voice::Passive,
				],				
				[
						'amusant',
						'amuser',
						Auxiliaire::Etre,
						'Participe',
						'Present',
						Gender::Masculine,
						Voice::Active,							
				],
				[
						'amusé',
						'amuser',
						Auxiliaire::Etre,
						'Participe',
						'Passe',
						Gender::Masculine,
						Voice::Active,							
				],
				[
						'amusée',
						'amuser',
						Auxiliaire::Etre,
						'Participe',
						'Passe',
						Gender::Feminine,
						Voice::Active,							
				],
				[
						'été amusé',
						'amuser',
						Auxiliaire::Etre,
						'Participe',
						'Passe',
						Gender::Masculine,
						Voice::Passive,							
				],
				[
						'été amusée',
						'amuser',
						Auxiliaire::Etre,
						'Participe',
						'Passe',
						Gender::Feminine,
						Voice::Passive,							
				]				
		];
	}
}
?>
