<?php
class ExceptionModel extends Enum
{
    const NO_EXCEPTIONS = 'no exceptions';
    // const WITHOUT_ISS_ENDING = 'without iss-ending';
    const ALLER = 'aller';
    const AVOIR_IRR = 'avoir_irr';
    const ETRE_IRR = 'etre_irr';
    const Eler_Ele = 'peler';
    const Eter_Ete = 'acheter';
    const Eler_Elle = 'appeler';
    const Eter_Ette = 'jeter';
    const ENVOYER = 'envoyer';
    const ARGUER = 'arguer';
    const CER = 'cer';
    const ECER = 'ecer';	
    const ESCER = 'escer';	
    const GER = 'ger';
    const IER = 'ier';
    const YER_YE_IE = 'yer_ye_ie';
    const YER_YE = 'yer_ye';
    const YER_IE = 'yer_ie';	
    const E_Akut_ER = 'e_akut_er';
    const E_Akut_ER2 = 'e_akut_er2'; // regular
    const E_Akut_CER = 'e_akut_cer';
    const E_Akut_GER = 'e_akut_ger';
    const E_Akut_IER = 'e_akut_ier'; // regular
	const E_Akut_IIER = 'e_akut_iier';
    const E_Akut_YER = 'e_akut_yer';
    const E_Er = 'e_er';
    const I_Trema_ER = 'i_trema_er'; // regular
    // OIR
    const DEVOIR = 'devoir';
    const FALLOIR = 'falloir';
    const MOUVOIR = 'mouvoir';
    const PLEUVOIR = 'pleuvoir';
    const POUVOIR = 'pouvoir';
    const SAVOIR = 'savoir';
    const VALOIR = 'valoir';
    const VOIR = 'voir';
    const RAMENTEVOIR = 'ramentevoir';
    const CHOIR = 'choir';
    const CHOIR2 = 'choir2';	
    const CEVOIR = 'cevoir';
    const SEOIR = 'seoir';
    const VOULOIR = 'vouloir';    
    // RIR
    const RIR = 'rir';
    const COURIR = 'courir';
    const FLEURIR = 'fleurir';
    const MOURIR = 'mourir';
    const QUERIR = 'querir';
    const DORMIR = 'dormir';
    const ENIR = 'enir';
    const BOUILLIR = 'bouillir';
    const CUEILLIR = 'cueillir';
    const FAILLIR = 'faillir';
    const SAILLIR = 'saillir';
    const TIR = 'tir';
    const VETIR = 'vetir';
    const FUIR = 'fuir';
    const SERVIR = 'servir';
    //
    const FAIRE = 'faire';
    const PLAIRE = 'plaire';
    const RAIRE = 'raire';
    const TAIRE = 'taire';
    const VAINCRE = 'vaincre';
    const DRE = 'dre';
    const PRENDRE = 'prendre';
    const INDRE = 'indre';
    const OINDRE = 'oindre';
 // the rules like -indre ...
    const COUDRE = 'coudre';
    const MOUDRE = 'moudre';
    const SOUDRE = 'soudre';
    const RESOUDRE = 'resoudre';
    const OCCIRE = 'occire';
    const CIRCONCIRE = 'circoncire';
    const DIRE = 'dire';
    const MAUDIRE = 'maudire';
    const SUFFIRE = 'suffire';
    const CONFIRE = 'confire';
    const LIRE = 'lire';
    const BOIRE = 'boire';
    const CROIRE = 'croire';
    const RIRE = 'rire';
    const CRIRE = 'crire';
    const FRIRE = 'frire';
    const UIRE = 'uire';
    const BRUIRE = 'bruire';
    const CLORE = 'clore';
    const ROMPRE = 'rompre';   
    const AITRE = 'paitre';
    const NAITRE = 'naitre';
    const OITRE = 'croitre';
    const ATTRE = 'battre';
    const METTRE = 'mettre';
    const FOUTRE = 'foutre';
    const CLURE = 'inclure';
    const SUIVRE = 'suivre';
    const VIVRE = 'vivre';
}
?>